#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend efex16.tech
        bind 0:80
        default_backend web_servers
backend web_servers
        balance roundrobin
        server 154503-web-01 54.159.24.194:80
        server 154503-web-02 54.208.205.82:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
